---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    15
    requiredRam:        1.0
    internetCheckUrl:   https://pardus.org.tr
    check:
        - storage
        - ram
        - power
        - root
    required:
        - storage
        - ram
        - root

autoInstall:
    enabled : true
    username: "pardus"
    password: "1"
    hostname: "pardus"
    fullname: "Pardus"
